version: "3"
output: interleaved
dotenv: [".env.local"]

tasks:
  post_create:
    desc: "Runs after this template is instantiated as a Sandbox or Bootstrap"
    cmds:
      - echo -e "To setup and run the app:\r\n"
      - echo -e "\tcd {{.ROOT_DIR}}\r"
      - echo -e "\tpnpm install\r"
      - echo -e "\tpnpm dev\r\n"

  install:
    desc: "Bootstrap application for local development"
    cmds:
      - "pnpm install"
